[package]
name = "substrate-keystore"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
derive_more = "0.14.0"
substrate-primitives = { path = "../primitives" }
parking_lot = "0.8.0"
